# Generated by Django 3.0.3 on 2020-09-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_eqpt_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleactionmodel',
            old_name='actionDate',
            new_name='ActionDate',
        ),
        migrations.RenameField(
            model_name='vehicleactionmodel',
            old_name='cost',
            new_name='Cost',
        ),
        migrations.RenameField(
            model_name='vehicleactionmodel',
            old_name='description',
            new_name='Description',
        ),
        migrations.RemoveField(
            model_name='vehicleactionmodel',
            name='VehicleRecord',
        ),
        migrations.AddField(
            model_name='vehicleactionmodel',
            name='Vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_eqpt_records.VehicleModel'),
        ),
        migrations.DeleteModel(
            name='VehicleRecordModel',
        ),
    ]
