# Generated by Django 3.0.3 on 2020-09-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eqpt_records', '0003_auto_20200920_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleactionmodel',
            name='ActionDate',
            field=models.DateTimeField(),
        ),
    ]
