# Generated by Django 3.0.3 on 2020-09-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_eqpt_records', '0005_auto_20200920_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleactionmodel',
            name='Vehicle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_eqpt_records.VehicleModel'),
            preserve_default=False,
        ),
    ]
