# Generated by Django 3.0.3 on 2020-09-21 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_eqpt_records', '0006_auto_20200920_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActionDate', models.DateField()),
                ('Description', models.TextField(null=True)),
                ('Cost', models.FloatField()),
                ('Title', models.CharField(max_length=200)),
                ('Placeholder', models.BooleanField(default=False)),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eqpt_records.VehicleModel')),
            ],
        ),
    ]
