# Generated by Django 3.0.3 on 2020-09-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eqpt_records', '0008_auto_20200921_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemodel',
            old_name='VINNumber',
            new_name='liscence_plate',
        ),
    ]
