# Generated by Django 3.0.3 on 2020-09-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eqpt_records', '0009_auto_20200921_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='Placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
